### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Gounlaf** [riotkit-org/file-repository#12]
# Enhancements

## Storage: flysystem integration

Right now, data are stored locally, on a pre-defined path (`$app['storage.path']`).

[Flysystem](http://flysystem.thephpleague.com/) is an awesome abstraction layer, and I think it should be embed by default.
It will add more flexibility about storage...

1. [Mandatory] Replace "manual storage management" with Flysystem (through [WyriHaximus/SliFly](https://github.com/WyriHaximus/SliFly))
2. [Optional] Since Flysystem provide multiple storages "definitions", we could support "storage choice" with different ways:
    * file type?
    * name (key) of storage send when requesting a new token?

## Global enhancements

* Re-dispatch methods in correct class
* Cleanup methods
* Re-dispatch exceptions
* Add method return type when possible
* Enhance comments
* Standardize input/output parameters name (`camelCase` or `snake_case`) ?

**TODO:** (Include existing feature that might be broken during implementation)
* [x] Replace all storage functionalities with Flysystem
* [ ] Tests...

* [x] POST /repository/image/add-by-url
* [x] POST /repository/image/upload
* [x] POST /repository/image/exists; **BC break:** change parameter `file_name` to `fileName` (`camelCase` in other routes)
* [x] POST /repository/image/delete; **BC break:** change parameter `file_name` to `fileId` (`camelCase` in other routes + delete with `publicId` since duplicate are allowed)
* [x] POST /repository/search/query; **BC break:** date is formatted as ISO8601
* [x] GET /repository/stats
* [x] GET /repository/routing/map
* [x] POST /auth/token/generate; **BC break:** existing table `tokens` is dropped then recreated with another schema
* [x] GET /jobs/token/expired/clear
* [x] GET /public/download/{imageName}
* [x] GET /public/upload/image/form
* [x] POST /public/upload/image
* [x] GET /public/upload/files/form
* [x] POST /public/upload/files
* [ ] Standardize input/output parameters name: `camelCase` or `snake_case`
* [x] Allow token to be send as "standard" Authorization header  (`Authorization: Bearer tokenvalue`-

**Comment by blackandred** [comment]
Hello,

I know Flysystem and I think probably it may be not bad idea as the filesystem would be more configurable via the dependency injection pattern.

**Comment by blackandred** [comment]
Everything that is touching the filesystem should be only here:
https://github.com/Wolnosciowiec/file-repository/blob/master/src/Manager/StorageManager.php

So it could be pretty easy to introduce flysystem that would be configurable via dependency injection.

There are a few things to be aware of:
- The flysystem does not distinct between directory and file (for example on FTP it's impossible, but the flysystem must be compatible with it)
- Flysystem throws different types of exceptions, and in other cases returns a boolean, in others throws exceptions comparing to the current code

**Comment by blackandred** [comment]
I would be against using the SliFly, I think that the Flysystem is simple enough to use it directly and create our own simple container definition for it.

**Comment by Gounlaf** [comment]
> I would be against using the SliFly, I think that the Flysystem is simple enough to use it directly and create our own simple container definition for it.
>
> The reason behind is also to keep the application small, so we do not need for every thing double dependencies first the original thing, second the integration with Silex/Pimple.

Ok, it's understable.

**Comment by blackandred** [comment]
If you would like to implement this I would be happy and it would be also nice to have some documentation for it :stuck_out_tongue:

**Comment by Gounlaf** [comment]
I can try. But I will have difficulties with tests :p
I was waiting for the other PR to be merged in order to start on a clean master :)

**Comment by blackandred** [comment]
Sure. Please take a look at the PR, test the functionality so I can have a reason to safely merge it :smile:

**Comment by blackandred** [comment]
Merged already dependent PR :+1:

**Comment by blackandred** [comment]
Don't be scared because of tests, it's pretty easy thing and it's good to learn how to test as its a common requirement in other community and commercial projects :wink: 

I can help you, guide how to test. You can submit some code and I can review.

Generally the rule is simple. You need to invoke something and check if its returning expected results. A good practice is to test smaller parts of code, method per method and to also create a functional test that tests some higher level code like a controller output.

**Comment by blackandred** [comment]
I just used Flysystem in other project, it's very nice and configurable.
https://github.com/zwiazeksyndykalistowpolski/php-denyhosts

So, it would be nice to see it also here.

**Comment by Gounlaf** [comment]
Hi @blackandred,

I'm working on PR, doing it "step by step" (1 commit for now on branch enhancement/flysystem-integration).

I'm looking into `StorageManager`, and I'm wondering if you would agree that I "simplify" methods `getUniquePathWhereToStorageFile`, `getPathWhereToStoreTheFile`, `getStorageFileName`, `getFileName` (they are all "related") :

* Looking if file exist (`getUniquePathWhereToStorageFile`) might take time if storage is remote, so I **suggest** to just generate a UUID ([ramsey/uuid](https://github.com/ramsey/uuid) - small, great one) and store the file under this name; it will be compatible with current File entity (since you store "filename" (the original one if I'm right) and the "path" (contentPath) separately
* Obviously, methods will not depends on the "storagePath", since paths will all be relative to the storage root of the choosen adapter
* Right now, I will handle only the "default" Flystem instance (local adapter, with web/storage as root) - kind of drop-in replacement of current implementation
* When everything is working correctly with "default" adapter, we will be able to take care of other "instances/configurations"

**Comment by blackandred** [comment]
Sure. Is there a possibility to keep the file names in the URL?
Currently we have something like: `g3ds2f-gastronomy-picket.jpg`
How would the download url look like?

I would suggest to not focus on remote implementations and leave a possibility to inject other adapter easily via dependency injection from configuration file. That would be flexible enough.

**Comment by Gounlaf** [comment]
> Sure. Is there a possibility to keep the file names in the URL?
> Currently we have something like: `g3ds2f-gastronomy-picket.jpg`
> How would the download url look like?

I think it will be almost the same (based on "original" file name)

> I would suggest to not focus on remote implementations and leave a possibility to inject other adapter easily via dependency injection from configuration file. That would be flexible enough.

If you can take a look to "the first commit" mentioned above.
Flysystem "instance" will be called like this :

```php
/* @var $flysystem \Service\FlysystemService */
$flysystem = $app['flysystem.instances']['default'];
```

* Since you suggest to keep the `StorageManager` and replace what need to be, I will need to find "the best way" to tell which "instance" should be used
* There are probably some class that need to be "cleaned": as example, `UploadByHttpActionHandler::moveUploadedFile` need to call `StorageManager` instead of moving file itself
* Theses class will also need to determinate which "instance" should be used (in order to tell it to `StorageManager`)

=> I'm working on it

**Comment by blackandred** [comment]
Do we need multiple instances?
I agree, the `UploadByHttpActionHandler::moveUploadedFile` probably needs to be refactored.
Sorry for that code made under deadline in the action handler...

I hope we will get into the perfection when there will be more than one person working on the project :stuck_out_tongue:

**Comment by blackandred** [comment]
btw. I guess that would not be nice to pass the whole `$app['flysystem.instances']` or `$app` to the `StorageManager`. Instead we should just decide on the container level in the `StorageManager` service definition which instance of flysystem to pick.

**Comment by Gounlaf** [comment]
> Do we need multiple instances?

Well, it's one flysystem instance per adapter.

So, two possibilities :
* We allow to have only one configured adapter (default the Local one): It will requires less modifications, but tie "user" to one configuration only
* We allow multiple configured adapters: It will requires more modifications, since we need to answer to several questions:
    * Who choose the "adapter"? the "user" that send a file to API? the owner of the file-repository?
    * If it's the owner, how the choice is made? depends on the file type? on the file size? (if there where OAuth2, it could be based on the client)
    * If it's the user, how the choice is made? a parameter send during the token generation? a parameter sent with the file?

... There could be a lot of questions.
I see "a case" (but not a common case): small files (images) could be on local storage, and big files on remote storage (AWS3 as example)

**Comment by Gounlaf** [comment]
> btw. I guess that would not be nice to pass the whole $app['flysystem.instances'] or $app to the StorageManager. Instead we should just decide on the container level in the StorageManager service definition which instance of flysystem to pick.

And so instanciate as many `StorageManager` as `Flysystem instance`? It would be a good idea.

**Comment by blackandred** [comment]
I suggest to now just implement the interface and do not care about the distinction between different adapters.

Why? Because it would be easy to inject those objects anywhere when we will have a complete idea how it could be practical in best way.

--
I was just thinking about basic replacement of filesystem usage to flysystem without having multiple instances of `StorageManager` to do not make this too complex.

I think that in the future we may be able to decide inside of `StorageManager` by passing eg. two implementations in the constructor and then in a method decide if use A or B depending on some conditions.

**Comment by Gounlaf** [comment]
Ok; fortunatly, what I've started is almost what you suggest:

* I've updated the StorageManager, passing it `$app['flysystem.instances']`
* I'm calling 'default' instance... by default (within a method that "choose" the right instance)

=>

* It prepares for "the future"
* We doesn't inject the whole Application|Container (if I'm right, it's called an anti-pattern)

**Comment by blackandred** [comment]
Sounds cool in my opinion.
About the injection of whole container - sorry, I had to be sure as we do not know that much yet, so I'm trying to explain everything from scratch :stuck_out_tongue: 

I'm impressed your in-depth analysis of the code, hehe. Should I be ashamed although a little of the code I wrote? :smile:

**Comment by Gounlaf** [comment]
> Sounds cool in my opinion.
👍 

> About the injection of whole container - sorry, I had to be sure as we do not know that much yet, so I'm trying to explain everything from scratch 😛
> 
> I'm impressed your in-depth analysis of the code, hehe. Should I be ashamed although a little of the code I wrote? 😄

Absolutely not! I just tried to summary, listing important points

**Comment by blackandred** [comment]
Nice. Sure, thanks :smile:

**Comment by blackandred** [comment]
Sorry, had to ask as I didn't had any contributions yet in any project on github. It means no feedback until now :stuck_out_tongue: 

Going back to topic. The Flysystem can increase the scalability of the application.
The application may be able to store files on shared space like Amazon, and the application could be scaled into many instances.

**Comment by Gounlaf** [comment]
@blackandred: https://github.com/Wolnosciowiec/file-repository/blob/master/src/Manager/FileRegistry.php#L145

Any reason to delete with hash instead of doing this? :

```php
$this->em->remove($file);
$this->em->flush();
```

Thanks

**Comment by blackandred** [comment]
I think it could be safely refactored. There is only one usage where entity IS ALREADY PERSISTED :smile: 
Thanks, after some time its nice that this older code could be simplified.

**Comment by Gounlaf** [comment]
Hi @blackandred,

Can you confirm me that json is not supported on routes `/repository/*`?

**Comment by blackandred** [comment]
What do you mean by not supported? As a payload or as a response?

**Comment by Gounlaf** [comment]
> What do you mean by not supported? As a payload or as a response?

As a payload. I found the json transformation mapped only on "public" routes (through the Form that re-dispatch a transformed payload to a standard "post" request with `$_FILES` filled)

**Comment by blackandred** [comment]
I don't remember every endpoint but looking at README I can see:

```
POST /repository/search/query
{
    "tags": [],
    "limit": 50,
    "offset": 0
}
```

We need to update postman collections file :smile:

**Comment by Gounlaf** [comment]
If you can do it, It would be nice.

I will re-verify again on a clean install from current version.

* POST /repository/image/add-by-url => JSON Payload supported
* POST /repository/image/upload => JSON Payload not (seems to be) supported

**Comment by blackandred** [comment]
Ok, I will take a look at possible automation of endpoints documentation.

**Comment by Gounlaf** [comment]
http://swagger.io :D
